/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ads;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author USER
 */
public class updatedialog extends javax.swing.JDialog {
    
    

    /**
     * Creates new form updatedialog
     */
    private String employee_id;
    
    public updatedialog(java.awt.Frame parent, boolean modal, String employee_id, String first_name, String last_name, String email, String department_id, String position, String shift_id) {
        super(parent, modal);
        initComponents();
        
         getContentPane().setBackground(new java.awt.Color(0,79,166));
         
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
         
        loadDepartments();
        loadShift();
        this.employee_id = employee_id;
        
        update_empid.setText(employee_id);
        update_empid.setEditable(false);
        
        update_fname.setText(first_name);
        update_lname.setText(last_name);
        update_email.setText(email);
        selectComboItem(update_dept, department_id);
        update_position.setSelectedItem(position);
        selectComboItem(update_shift, shift_id);
        
    }
    
    
    private void selectComboItem(javax.swing.JComboBox<String> combo, String value) {
    for (int i = 0; i < combo.getItemCount(); i++) {
        String item = combo.getItemAt(i);
        // Match by ID (e.g. "1") OR by name (e.g. "Morning Shift")
        if (item.startsWith(value + " - ") || item.endsWith(" - " + value) || item.equals(value)) {
            combo.setSelectedIndex(i);
            return;
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        update_dept = new javax.swing.JComboBox<>();
        update_position = new javax.swing.JComboBox<>();
        update_shift = new javax.swing.JComboBox<>();
        update_fname = new javax.swing.JTextField();
        update_lname = new javax.swing.JTextField();
        update_email = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        update_empid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        clearbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));

        update_dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"}));

        update_position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operations Officer", "CSR", "Bank Teller", "Loan Officer", "Staff Accountant", "IT Support Specialist", "HR Officer", "Compliance Officer", "Treasury Analyst", "Marketing Officer"})
        );

        update_shift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        update_fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                update_fnameKeyTyped(evt);
            }
        });

        update_lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                update_lnameKeyTyped(evt);
            }
        });

        savebtn.setBackground(new java.awt.Color(254, 177, 12));
        savebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        savebtn.setForeground(new java.awt.Color(255, 255, 255));
        savebtn.setText("SAVE");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(254, 177, 12));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                                 UPDATE EMPLOYEE");
        jLabel1.setOpaque(true);

        clearbtn.setBackground(new java.awt.Color(254, 177, 12));
        clearbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearbtn.setForeground(new java.awt.Color(255, 255, 255));
        clearbtn.setText("CLEAR");
        clearbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearbtnMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee Number:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last Name:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Department:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Position:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Shift:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(update_fname, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(update_position, javax.swing.GroupLayout.Alignment.TRAILING, 0, 232, Short.MAX_VALUE)
                    .addComponent(update_shift, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update_dept, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update_email, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(update_lname, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(update_empid))
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_empid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update_shift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
    
                 if (update_fname.getText().trim().isEmpty() ||
                 update_lname.getText().trim().isEmpty() ||
                 update_email.getText().trim().isEmpty() ||
                 update_position.getSelectedItem() == null ||
                 update_dept.getSelectedItem() == null ||
                 update_shift.getSelectedItem() == null) {

                 JOptionPane.showMessageDialog(this,
                     "All fields are required. Please fill in everything."
                     );
                 return; // stop here
             }
                 
    String first_name = update_fname.getText();
    String last_name  = update_lname.getText();
    String email      = update_email.getText();
    String position   = update_position.getSelectedItem().toString();

    // Split to get only the ID number from "3 - Teller Services"
    int department_id = Integer.parseInt(update_dept.getSelectedItem().toString().split(" - ")[0].trim());
    int shift_id      = Integer.parseInt(update_shift.getSelectedItem().toString().split(" - ")[0].trim());

    try {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc:sqlserver://localhost:1433;" +
                     "databaseName=attendance_sys;" +
                     "user=sa;" +
                     "password=sean;" +
                     "encrypt=true;" +
                     "trustServerCertificate=true;";

        Connection con = DriverManager.getConnection(url);

        String updateQuery = "UPDATE Employees SET first_name=?, last_name=?, position=?, department_id=?, email=?, shift_id=? WHERE employee_id=?";

        PreparedStatement ps = con.prepareStatement(updateQuery);
        ps.setString(1, first_name);
        ps.setString(2, last_name);
        ps.setString(3, position);
        ps.setInt(4, department_id);
        ps.setString(5, email);
        ps.setInt(6, shift_id);
        ps.setString(7, employee_id);

        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Update Successfully");
        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }

    }//GEN-LAST:event_savebtnActionPerformed

    private void clearbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearbtnMouseClicked
        update_fname.setText("");
        update_lname.setText("");
        update_email.setText("");
        update_dept.setSelectedIndex(-1); // resets to blank first item
        update_position.setSelectedIndex(-1);   // resets to blank first item
        update_shift.setSelectedIndex(-1);      // resets to blank first item
        update_fname.requestFocus();             // puts cursor back on first field
    }//GEN-LAST:event_clearbtnMouseClicked

    private void update_fnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_update_fnameKeyTyped
                        if (Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_update_fnameKeyTyped

    private void update_lnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_update_lnameKeyTyped
                if (Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }       
    }//GEN-LAST:event_update_lnameKeyTyped

    
    
    private void loadDepartments() {
    try {
        String url = "jdbc:sqlserver://localhost:1433;"
                   + "databaseName=attendance_sys;"
                   + "encrypt=true;"
                   + "trustServerCertificate=true;";

        Connection con = DriverManager.getConnection(url, "sa", "sean");

        String sql = "SELECT departmen"
                + "t_id, department_name FROM Departments";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        update_dept.removeAllItems();

        while (rs.next()) {
            update_dept.addItem(
                rs.getInt("department_id") + " - " +
                rs.getString("department_name")
            );
        }
          update_dept.setSelectedIndex(-1);
        rs.close();
        pst.close();
        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
    
    private void loadShift() {
    try {
        String url = "jdbc:sqlserver://localhost:1433;"
                   + "databaseName=attendance_sys;"
                   + "encrypt=true;"
                   + "trustServerCertificate=true;";

        Connection con = DriverManager.getConnection(url, "sa", "sean");

        String sql = "SELECT shift_id, shift_name FROM Shifts";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        update_shift.removeAllItems();
        
        while (rs.next()) {
            update_shift.addItem(
                rs.getInt("shift_id") + " - " +
                rs.getString("shift_name")
            );
        }
        
        update_shift.setSelectedIndex(-1);

        rs.close();
        pst.close();
        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton savebtn;
    private javax.swing.JComboBox<String> update_dept;
    private javax.swing.JTextField update_email;
    private javax.swing.JTextField update_empid;
    private javax.swing.JTextField update_fname;
    private javax.swing.JTextField update_lname;
    private javax.swing.JComboBox<String> update_position;
    private javax.swing.JComboBox<String> update_shift;
    // End of variables declaration//GEN-END:variables
}
